### ISSUE TITLE
Dependency tree is broken if no `yarn.lock` is used

### ISSUE THREAD

**Issue by sneridagh** [plone/create-volto-app#19]
If you rebuild from an empty `yarn.lock` the dependency is broken. See details in #18.

For now, it's solved by reusing "old" inherited through time `yarn.lock`, but it's worth to take care of it at some point.

**Comment by nileshgulia1** [comment]
I too do not find a perfect one step solution for it. Maybe we have to manually keep pushing `yarn.lock` in template to avoid versioning problems. Maybe @robgietema  may have some other opinion in mind.

**Comment by avoinea** [comment]
I think this is deprecated.
