### ISSUE TITLE
Plone Volto - Create-Volto-App Unable To Install @plone/volto

### ISSUE THREAD

**Issue by andreasma** [plone/create-volto-app#21]
I tried to create a Volto app within my cloned Github repository github.com/plone/volto following the instructions in the readme file.
I installed yarn and @plone/create-volto-app using npm.
The command create-volto-app myvoltoapp failed with:

--------  output in the shell  ---------

Creating myvoltoapp...

    Success! Created files for "myvoltoapp" Volto app

Installing npm modules:
@plone/volto

    Error! Failed to install @plone/volto, try again.
    undefined

---------------- end of output in the shell --------------------

I'm using openSuSE Leap 15.1 (x64) with installed nodejs8  from the openSuSE repos:
nodejs8-8.17.0-lp151.2.12.1.x86_64
nodejs8-devel-8.17.0-lp151.2.12.1.x86_64

npm -v is:
6.14.4

**Comment by tisto** [comment]
@andreasma Volto supports Node 10 and 12. Those are the LTS versions. Node 8 is outdated. Please update your Node installation.

**Comment by tisto** [comment]
@nileshgulia1 @sneridagh @robgietema I am wondering if there is a way we can detect the node version that is used and return a nice error string instead of just breaking with undefined?

**Comment by tisto** [comment]
Just for the record. Node 8 reached its end-of-life in December 2019: 

https://github.com/nodejs/Release#end-of-life-releases

So we will not put any effort into maintaining this. Two node versions are more than enough to maintain. :)

**Comment by nileshgulia1** [comment]
@tisto Yes I think a proper error message will be appropriate which prompts out on outdated `node` versions.
